version: '1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-systudent
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: systudent
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - custom-red  
      
      
  systudent-db:
    build: .
    container_name: systudent-db
    image: systudent-db
    ports:
      - "8086:8086"
    networks:
      - custom-red
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-systudent:3306/systudent?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://systudent-discovery:8761/eureka
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_APPLICATION_NAME: docker-systudent-db


networks:
  custom-red:
    external: true