version: '1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-systudent
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: systudent
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - custom-red  
networks:
  custom-red:
    external: true